<a href="https://colab.research.google.com/github/Paulina99Sadowska/Artificial_Intelligence/blob/main/ANN_for_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Classification Artificial neural networks for the category dependent variable


opis problemu

### Importing the libraries

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf

## Part 1 - Data Preprocessing

### Importing the dataset

In [ ]:
dataset = pd.read_csv('alzheimer.csv')
M = dataset.iloc[:, 4].values

ilosc_nan = np.isnan(M).sum()
print(ilosc_nan)


dataset.dropna(subset=['SES'], inplace=True)
print(dataset)



#num_missing_values = X.count(None)
#print(num_missing_values)

#dataset = dataset.drop('SES', axis=1)

#X = dataset.iloc[:, 1:9].values
#print(X)

#y = dataset.iloc[:, 0].values
#np.unique(y)

19
           Group M/F  Age  EDUC  SES  MMSE  CDR  eTIV   nWBV    ASF
0    Nondemented   M   87    14  2.0  27.0  0.0  1987  0.696  0.883
1    Nondemented   M   88    14  2.0  30.0  0.0  2004  0.681  0.876
5    Nondemented   F   88    18  3.0  28.0  0.0  1215  0.710  1.444
6    Nondemented   F   90    18  3.0  27.0  0.0  1200  0.718  1.462
7    Nondemented   M   80    12  4.0  28.0  0.0  1689  0.712  1.039
..           ...  ..  ...   ...  ...   ...  ...   ...    ...    ...
368     Demented   M   82    16  1.0  28.0  0.5  1693  0.694  1.037
369     Demented   M   86    16  1.0  26.0  0.5  1688  0.675  1.040
370  Nondemented   F   61    13  2.0  30.0  0.0  1319  0.801  1.331
371  Nondemented   F   63    13  2.0  30.0  0.0  1327  0.796  1.323
372  Nondemented   F   65    13  2.0  30.0  0.0  1333  0.801  1.317

[354 rows x 10 columns]


### Encoding categorical data

Label Encoding the "Gender" column

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [ ]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [ ]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
print(X_train)

[[0.0 0.0 1.0 ... 1 0 163830.64]
 [0.0 1.0 0.0 ... 1 1 57098.0]
 [1.0 0.0 0.0 ... 1 0 185630.76]
 ...
 [1.0 0.0 0.0 ... 1 0 181429.87]
 [0.0 0.0 1.0 ... 1 1 148750.16]
 [0.0 1.0 0.0 ... 1 0 118855.26]]


### Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

print(X_train)

[[-1.01460667 -0.5698444   1.74309049 ...  0.64259497 -1.03227043
   1.10643166]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
  -0.74866447]
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.48533467]
 ...
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.41231994]
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497  0.9687384
   0.84432121]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497 -1.03227043
   0.32472465]]


## Part 2 - Building the ANN

### Initializing the ANN

In [ ]:
#create ANN as an object of a certain class
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [ ]:
#dense class belongsto a certain path of libraries, the root of this lib is tf
#units - corresponds to the number of neurons (hidden neurons) z iloma zmiennymio chcemy połączenia
# tym parametrem możemy manipulować
#activation - jaka funkcja relu - rectify /
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [ ]:
#sigmoid - bo mamy prawdopodobieństwo że nasze y=1
##UWAGA dla non-binary soft max
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [ ]:
#adam optimizer - performance optimizer tht can perform SGD
#adjust a weights
#binary - "binary_crossentropy"
#UWAGA dla non-binary categorical_crossentropy (chyba)
#metrics - można urzyć kilku na raz , one będą oceniać ANN during training, but we choose only one - accuracy - można poszukać innych
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

NameError: ignored

### Training the ANN on the Training set

In [ ]:
#method to TRAIN a ML models is always FIT
#batch_size - give the number of predictions you want to have in the batch to y^ and  y be compared
#batch learning is always more efficient and more performance - to jest ta opcja mieszana gdzie kilka predictions to several real results into a batch
#default value is 32
#epochs - arbitralna granica, ogólnie definiowana jako „jedno przejście przez cały zbiór danych”,
#używana do rozdzielania uczenia na odrębne fazy, co jest przydatne do rejestrowania i okresowej oceny
#not too small
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

NameError: ignored

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

In [ ]:
#sc = StandardScaler() - nasza ANN jest nauczona na przeskalowanych wartościach więc musimy je przeskalować
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

[[False]]


### Predicting the Test set results

In [ ]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1516   79]
 [ 200  205]]


0.8605